/**
 * AUTO-GENERATED by apps/mobile/scripts/generate-voice-pack.mjs -- do not
 * hand-edit (regenerate by re-running that script; see docs/voice-pack.md).
 * Metro needs a static, literal `require(...)` call per bundled asset, so
 * this module lists every voice clip mp3 that currently exists under
 * apps/mobile/assets/voice/ as an explicit property. EMPTY (no `require`
 * calls) until clips have been generated -- the app builds and runs
 * correctly with an empty map, falling back to expo-speech for every cue
 * (MUST DO #3, ADR-0004's offline mandate: no clip here is ever fetched at
 * runtime, only bundled).
 *
 * `safeRequire` exists for vitest/vite-node, which has no mp3 asset pipeline:
 * there the require throws at load and the entry resolves to `undefined`,
 * reproducing the pre-generation (empty-map) behavior tests were written
 * against. Metro still statically collects the literal require inside the
 * thunk, so device bundling is unaffected.
 */
import type { BrakeUtteranceId } from './voiceCoach';

function safeRequire(load: () => number): number | undefined {
  try {
    return load();
  } catch {
    return undefined;
  }
}

export const VOICE_CLIPS: Partial<Record<BrakeUtteranceId, number>> = {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  'brake-hard': safeRequire(() => require('../../assets/voice/brake-hard.mp3')),
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  'brake': safeRequire(() => require('../../assets/voice/brake.mp3')),
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  'lift': safeRequire(() => require('../../assets/voice/lift.mp3')),
};
