/**
 * AUTO-GENERATED by apps/mobile/scripts/generate-voice-pack.mjs -- do not
 * hand-edit (regenerate by re-running that script; see docs/voice-pack.md).
 * Metro needs a static, literal `require(...)` call per bundled asset, so
 * this module lists every voice clip mp3 that currently exists under
 * apps/mobile/assets/voice/ as an explicit property. EMPTY (no `require`
 * calls) until clips have been generated -- the app builds and runs
 * correctly with an empty map, falling back to expo-speech for every cue
 * (MUST DO #3, ADR-0004's offline mandate: no clip here is ever fetched at
 * runtime, only bundled).
 */
import type { BrakeUtteranceId } from './voiceCoach';

export const VOICE_CLIPS: Partial<Record<BrakeUtteranceId, number>> = {};
