"""Voice candidates for the listening comparison: metadata + the config each one maps to."""
from __future__ import annotations

# id -> sample file stem, display info, and the `voices.en` config that selects it in the engine.
CANDIDATES = [
    # --- the voices the user already picked by ear for YOUTUBE_FARM (am_santa excluded on request) ---
    {"id": "kokoro_bm_lewis", "group": "farm", "name": "Kokoro — Lewis (UK)",
     "engine": {"engine": "kokoro", "voice": "bm_lewis"},
     "about": "Your pick for Dark History.", "cost": "free, local, Apache 2.0", "speed": "<1 s"},
    {"id": "kokoro_bm_george", "group": "farm", "name": "Kokoro — George (UK)",
     "engine": {"engine": "kokoro", "voice": "bm_george"},
     "about": "Your pick for Space.", "cost": "free, local, Apache 2.0", "speed": "<1 s"},
    {"id": "kokoro_af_heart", "group": "farm", "name": "Kokoro — Heart (US, female)",
     "engine": {"engine": "kokoro", "voice": "af_heart"},
     "about": "Your pick for Psychology.", "cost": "free, local, Apache 2.0", "speed": "<1 s"},
    {"id": "piper_vctk_spk020", "group": "farm", "name": "Piper — VCTK speaker 20 (UK)",
     "engine": {"engine": "piper", "voice": "en_GB-vctk-medium:20",
                "credit": "Voice: VCTK corpus, CSTR, University of Edinburgh (CC BY 4.0)"},
     "about": "The Business Collapse voice. CC BY 4.0: the credit line is added to the post caption automatically.",
     "cost": "free, local", "speed": "<1 s"},
    # --- local neural models on the GPU (free, commercial use allowed) ---
    {"id": "chatterbox_calm", "group": "local", "name": "Chatterbox — calm",
     "engine": {"engine": "chatterbox", "voice": "calm"},
     "about": "Resemble AI, MIT license. Expressive, very human delivery; lower exaggeration for a calm coach tone.",
     "cost": "free, runs on your RTX 5070", "speed": "≈30 s of audio in ≈17 s"},
    {"id": "chatterbox_default", "group": "local", "name": "Chatterbox — default",
     "engine": {"engine": "chatterbox", "voice": "default"},
     "about": "Same model, default energy.", "cost": "free, local", "speed": "≈30 s in ≈18 s"},
    {"id": "chatterbox_turbo", "group": "local", "name": "Chatterbox Turbo",
     "engine": {"engine": "chatterbox", "voice": "turbo"},
     "about": "Faster Chatterbox variant.", "cost": "free, local", "speed": "≈36 s in ≈12 s"},
    {"id": "kokoro_am_michael", "group": "local", "name": "Kokoro — Michael (US)",
     "engine": {"engine": "kokoro", "voice": "am_michael"},
     "about": "Kokoro-82M, Apache 2.0. Tiny, clean, very consistent.", "cost": "free, local", "speed": "≈30 s in <2 s"},
    {"id": "kokoro_am_fenrir", "group": "local", "name": "Kokoro — Fenrir (US)",
     "engine": {"engine": "kokoro", "voice": "am_fenrir"}, "about": "Kokoro, deeper male.", "cost": "free, local", "speed": "<1 s"},
    {"id": "kokoro_am_puck", "group": "local", "name": "Kokoro — Puck (US)",
     "engine": {"engine": "kokoro", "voice": "am_puck"}, "about": "Kokoro, brighter male.", "cost": "free, local", "speed": "<1 s"},
    {"id": "kokoro_af_bella", "group": "local", "name": "Kokoro — Bella (US, female)",
     "engine": {"engine": "kokoro", "voice": "af_bella"}, "about": "Kokoro, warm female.", "cost": "free, local", "speed": "<1 s"},
    {"id": "kokoro_bm_fable", "group": "local", "name": "Kokoro — Fable (UK)",
     "engine": {"engine": "kokoro", "voice": "bm_fable"}, "about": "Kokoro, British male, lighter.", "cost": "free, local", "speed": "<1 s"},
    {"id": "dia_seed1", "group": "local", "name": "Dia 1.6B — voice A (sample only)", "engine": None,
     "about": "Nari Labs, Apache 2.0. Very natural rhythm, but it invents a random voice each run; "
              "using it needs a reference clip to lock the voice. Not wired into the engine yet.",
     "cost": "free, local", "speed": "slow (minutes per clip)"},
    {"id": "dia_seed2", "group": "local", "name": "Dia 1.6B — voice B (sample only)", "engine": None,
     "about": "Same model, another random voice.", "cost": "free, local", "speed": "slow"},
    # --- Microsoft edge-tts (free, online) ---
    {"id": "edge_andrew_CURRENT", "group": "edge", "name": "Andrew — CURRENT voice",
     "engine": {"engine": "edge", "voice": "en-US-AndrewNeural", "rate": "+6%"},
     "about": "What the clips use today.", "cost": "free (online)", "speed": "instant"},
    {"id": "edge_andrew_multilingual", "group": "edge", "name": "Andrew Multilingual",
     "engine": {"engine": "edge", "voice": "en-US-AndrewMultilingualNeural", "rate": "+0%"},
     "about": "Newer, more conversational version of the same voice.", "cost": "free (online)", "speed": "instant"},
    {"id": "edge_brian_multilingual", "group": "edge", "name": "Brian Multilingual",
     "engine": {"engine": "edge", "voice": "en-US-BrianMultilingualNeural", "rate": "+0%"},
     "about": "Casual, approachable male.", "cost": "free (online)", "speed": "instant"},
    {"id": "edge_ava_multilingual", "group": "edge", "name": "Ava Multilingual (female)",
     "engine": {"engine": "edge", "voice": "en-US-AvaMultilingualNeural", "rate": "+0%"},
     "about": "Expressive female.", "cost": "free (online)", "speed": "instant"},
    {"id": "edge_emma_multilingual", "group": "edge", "name": "Emma Multilingual (female)",
     "engine": {"engine": "edge", "voice": "en-US-EmmaMultilingualNeural", "rate": "+0%"},
     "about": "Friendly female.", "cost": "free (online)", "speed": "instant"},
    {"id": "edge_christopher", "group": "edge", "name": "Christopher",
     "engine": {"engine": "edge", "voice": "en-US-ChristopherNeural", "rate": "+0%"},
     "about": "News-reader authority.", "cost": "free (online)", "speed": "instant"},
    {"id": "edge_ryan_uk", "group": "edge", "name": "Ryan (UK)",
     "engine": {"engine": "edge", "voice": "en-GB-RyanNeural", "rate": "+0%"},
     "about": "British male.", "cost": "free (online)", "speed": "instant"},
]
