import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { Elm327ResponseFramer } from '../../src/telemetry';

describe('ELM327 response framing', () => {
  it('parses identically for every generated byte split', () => {
    const stream = '010C\r41 0C 1A F8\r>NO DATA\r>OK\r>';
    const expected = ['010C\r41 0C 1A F8\r', 'NO DATA\r', 'OK\r'];

    fc.assert(
      fc.property(
        fc.array(fc.boolean(), { minLength: stream.length - 1, maxLength: stream.length - 1 }),
        (splitAfter) => {
          const chunks: string[] = [];
          let chunk = stream[0] ?? '';
          for (let index = 0; index < splitAfter.length; index += 1) {
            if (splitAfter[index]) {
              chunks.push(chunk);
              chunk = '';
            }
            chunk += stream[index + 1] ?? '';
          }
          chunks.push(chunk);

          const framer = new Elm327ResponseFramer();
          const actual = chunks.flatMap((part) => framer.push(part));
          expect(actual).toEqual(expected);
        },
      ),
      { numRuns: 300 },
    );
  });
});
